### ISSUE TITLE
Logo Design For Random Image

### ISSUE THREAD

**Issue by zularizal** [jeisfeld/RandomImage#1]
Hello @jeisfeld , I want to contribute to your project, I want to design a logo for your project, it's free, what do you think?

**Comment by jeisfeld** [comment]
Hi, I don't understand the motivation behind your question. Why do you see the need to design a logo?

**Comment by zularizal** [comment]
Because I think the current logo looks less interesting, I want to create a new logo with a new style.

**Comment by jeisfeld** [comment]
Well, on the one hand, I'd be interested to see your idea. On the other hand, I want to "own" the project, don't want to have any "licensing debt" and don't want to promise in advance to use your logo.

**Comment by jeisfeld** [comment]
By the way: I assume you are referring to the app logo (and not to my non-existing github logo)?

**Comment by zularizal** [comment]
Okay, I agree with you, The logo I will make is licensed gpl-v2, you can use it freely.

I found the logo with the name ic_launcher_web.png on your repository, I think it is your project logo. Therefore I suggest a new logo.

**Comment by jeisfeld** [comment]
Fine - I would be glad to see your proposal :-).

**Comment by zularizal** [comment]
Hi, can you give me about the description of the app?

**Comment by jeisfeld** [comment]
Hi, I don't understand what you want (and for what purpose).

**Comment by zularizal** [comment]
Sorry because before I was busy because of a problem in college. I want to create a logo for your project. So I need a description of your app.

**Comment by jeisfeld** [comment]
Hi, I don't understand what kind of description you need in order to create a logo.

Short description might be: "This app allows you to select an arbitrary number of images and folders that are stored on your smartphone (or tablet, including SD card) into a list, and then, whenever you want, to get one random photo out of your list displayed."

**Comment by zularizal** [comment]
Okay, I think this is enough information. I will send a logo or icon sample to you after I design the logo.

**Comment by zularizal** [comment]
Hi @jeisfeld , this is some logo design for your project. What do you think?

And which one do you like?
If there is something you want to change, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/46454578-00c80180-c7d1-11e8-9078-039eeb7883eb.png)

**Comment by jeisfeld** [comment]
Hi,

thanks - I like the second one most.

Somehow, I am reluctant to make a change of the logo (which is also the
launcher icon) which changes everything completely. Therefore I thought of
using colors from the original logo.

Moreover, there are two variants of the launcher icon - one for displaying
an image and one for changing the settings.

Therefore I'd propose to try the following ones.

[image: ic_launcher.png] [image: ic_launcher_setup.png]

(I first tried without the green area, but these somehow appear "too empty"
on the home screen.)

What do you think about this variant?

Regards

Jörg



Am Do., 4. Okt. 2018 um 07:31 Uhr schrieb Zularizal <
notifications@github.com>:

**Comment by jeisfeld** [comment]
![ic_launcher](https://user-images.githubusercontent.com/7068726/46481371-88bf0300-c7f3-11e8-9fac-7f62c63f09d6.png)
![ic_launcher_setup](https://user-images.githubusercontent.com/7068726/46481372-88bf0300-c7f3-11e8-9844-ca4137539199.png)

**Comment by zularizal** [comment]
I think it's a good variant because it doesn't eliminate the original shape of the logo.

I have designed according to the variant you want. In the main logo, I have reduced the "too empty".
And here I use material color. What do you think? Are there any colors you like or do you want other colors?

![bitmap1](https://user-images.githubusercontent.com/38547278/46510061-d594ef00-c870-11e8-91f6-3f79b3ed250f.png)

**Comment by jeisfeld** [comment]
I just wonder if we are talking about the same thing.

What are you referring too when talking about "logo for the project"?

I thought that you suggested to replace the existing ![App Logo](https://github.com/jeisfeld/RandomImage/blob/master/RandomImageIdea/randomImageLib/src/main/res/drawable-xxxhdpi/ic_launcher.png)

Now I wonder if you at all refer to this app logo, or if you instead refer to the logo of my user @jeisfeld here in Github (which up to now is just default logo)?

**Comment by zularizal** [comment]
Sorry, I misunderstood your previous intent.

Yes, I refer to the new logo for your project. No problem, if you don't want to change the logo (icon launcher). Maybe I can help other things for your project.

**Comment by jeisfeld** [comment]
From your response it is still unclear what you refer to.
Do you refer to the launcher icon or to the Github user logo?

Regarding the icon launcher, as I said, I am reluctant to completely change everything so that existing users don't recognize anything any more. This is why I thought of reusing the colors of the existing icon (as depicted above).

When testing it, I noticed that generally it is irritating if there is lots of transparency in the middle part of a launcher icon - this is why I added the green background in the sample above. (And this is why the vast majority of launcher icons have a form that is overall close to square or oval - even the sharp edges of the arrows in the new icon give me a slightly strange feeling when seeing them on the home screen.)

**Comment by zularizal** [comment]
I refer to the icon launcher.

In my opinion, the logo and icon are a little different.
I have previously contributed to another project. After I made a logo for them, I also made an icon (the center is not transparent) for their project.
Here's an example: https://github.com/eyedol/checkin/issues/24#issuecomment-423797868

**Comment by zularizal** [comment]
Okay, you're right too. A new logo will affect existing users.

I will close this issue.

**Comment by jeisfeld** [comment]
Ok - I'm sorry if my reaction is frustrating. I'll keep your design proposals in mind.
